CREATE DATABASE IF NOT EXISTS magerwa_vts CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE magerwa_vts;

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    names VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL,
    national_id VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    api_token VARCHAR(80) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    names VARCHAR(150) NOT NULL,
    national_id VARCHAR(30) NOT NULL UNIQUE,
    telephone VARCHAR(30) NOT NULL,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chassis_number VARCHAR(80) NOT NULL UNIQUE,
    manufacture_company VARCHAR(120) NOT NULL,
    manufacture_year SMALLINT NOT NULL,
    price DECIMAL(15,2) NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    client_id INT DEFAULT NULL,
    plate_number VARCHAR(30) DEFAULT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicle_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB;
